---
title: "daie_ca4"
author: "Conor Crean"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Clear console on each execute and set chunk default to not show code
# Connect (and create) a new local SQLite DB
```{r echo = FALSE}

cat("\014")


library(pacman)
pacman::p_load(dbplyr,RSQLite,rmarkdown)

dbfile <- "daie_ca4_db.sqlite"
if (file.exists(dbfile))
  {file.remove(dbfile)
}


daie_ca4_db <- dbConnect(RSQLite::SQLite(), dbfile)

```

## Download and load libraries

```{r}
if(!require("RMySQL"))
  install.packages("RMySQL")
if(!require("dplyr"))
  install.packages("dplyr")
if(!require("readr"))
install.packages("readr")
if(!require("DBI"))
install.packages("DBI")


library(DBI)
library(RMySQL)
library(readr)
library(dplyr)






```







# Test the DB

```{r}


return <- dbExecute(daie_ca4_db,"CREATE TABLE Groups (
   id_number integer NOT NULL CONSTRAINT Group_pk PRIMARY KEY, Name varchar(50) NOT NULL")







```

# Query and store the results

# Execute a query with no result

```{r}

result <- dbGetQuery(conn, "SELECT * FROM Asset ")
result


```
#Add to database
```{r echo = FALSE}

return <- dbExecute(daie_ca4_db,"INSERT INTO Asset
                    (id_number,Name )
                    VALUE
                    (1, 'Weapon')")
return <- dbExecute(daie_ca4_db,"INSERT INTO Asset
                    (id_number,Name )
                    VALUE
                    (2, 'Armour')")
return <- dbExecute(daie_ca4_db,"INSERT INTO Asset
                    (id_number,Name )
                    VALUE
                    (3, 'Picture')")
return <- dbExecute(daie_ca4_db,"INSERT INTO Asset_for_Library
                    (Asset_id_number,Library_id_number, )
                    VALUE
                    (3, 'Picture')")

```



# Do NOT forget to disconnect - otherwise we may hit a remote connection limit

```{r echo=FALSE}



dbDisconnect(daie_ca4_db)


```
