---
title: "PartB CA4"
author: "Conor Crean"
date: "`r Sys.Date()`"
output: html_document
---

#Assumptions
The variables chosen include age and the average monthly hours of gaming.
My assumption that as players age the less hours that they can dedicated to playing video games due to work and other commitments.




#Linear Regression Analysis


##### *Data Overview*
```{r , echo=FALSE}
#Library for graphs and data presentation loaded
library(readr)
library(tidyverse)
library(ggplot2)


#data assigned to a variable
daie_ca4_game_data <- read_csv("amalgamated_game_survey_250_2022.csv")


#Data checked head and tails along with summary
#View(daie_ca4_game_data)
head(daie_ca4_game_data,5)
tail(daie_ca4_game_data,5)
summary(daie_ca4_game_data)




```


```{r , echo=FALSE}

library('statsr')

hist(daie_ca4_game_data$age )
hist(daie_ca4_game_data$avg_monthly_expenditure_dlc  )  

cor(daie_ca4_game_data$age, daie_ca4_game_data$avg_monthly_hrs_gaming)


plot_ss(age, avg_monthly_hrs_gaming, daie_ca4_game_data)

m1 <- lm(age ~ avg_monthly_hrs_gaming, data = daie_ca4_game_data)
summary(m1)


plot(daie_ca4_game_data$age ~ daie_ca4_game_data$avg_monthly_hrs_gaming)
abline(m1)


plot(m1$residuals ~ daie_ca4_game_data$avg_monthly_hrs_gaming)
abline(h = 0, lty = 3)  # adds a horizontal dashed line at y = 0

hist(m1$residuals)


qqnorm(m1$residuals)
qqline(m1$residuals) 


ggplot(daie_ca4_game_data,aes(age, avg_monthly_hrs_gaming)) +
  geom_point() +
  geom_smooth(method='lm')



ggplot(daie_ca4_game_data,aes(gender, avg_monthly_hrs_gaming)) +
  geom_point() +
  geom_smooth(method='lm')


```